### ISSUE TITLE
User Can Sort Their Entries By Date Created

### ISSUE THREAD

**Issue by adrienne-yung** [adrienne-yung/code-journal#9]
## 💰 Motivation

Provide the user the option of selecting/viewing an entry by the order in which they posted.

## 📐 Plan

Allow users to sort their entries by newest to oldest & oldest to newest

## ✅ Task List

- [ ] In your index.html, create a form that allows users to select the desired options.
- [ ] Add an event listener when newest to oldest radio input is chosen, in which entries are sorted from higher entryId to lowest entryId
- [ ] Add an event listener when oldest to newest radio input is chosen, in which entries in your entry list are sorted from lowest entryId to highest entryId 
- [ ] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [ ] Test all functionality again in a private browsing session.
- [ ] Fix all errors.
